on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]

name: Publish To Docker & Okteto

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    ##########################
    # Checkout the code base #
    ##########################
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: marianrap/sip-okteto-python
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./Dockerfile
        tags: "latest,${{ github.sha }}"
    ##########################
    #     Detect Secrets     #
    ##########################
    - name: Detect Secrets
      uses: max/secret-scan@master
    ##########################
    #       Trivy Scan       #
    ##########################
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker.io/marianrap/sip-okteto-python:${{ github.sha }}'
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'
    ##########################
    #  Deploy K8S to Okteto  #
    ##########################
    
    - name: Verify functioning
      uses: Consensys/kubernetes-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: get pods
    
    - name: Deploy to Cluster 2
      uses: Consensys/kubernetes-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: set image --record deployment/flaskapp-deployment flaskapp=marianrap/sip-okteto-python:${{ github.sha }}
     
    - name: Verify deployment 2
      uses: Consensys/kubernetes-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: rollout status deployment/flaskapp-deployment   